[package]
name = "untitled"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28", features = ["full"] }
sqlparser = { version = "0.35", features = ["serde", "serde_json", "json_example"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.120"